config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#top'
  
  get 'users/:id/edit' => 'users#edit'
  post 'users/:id/update' => 'users#update'
  get 'users/:id/favorites' => 'users#favorites'
  post 'users/create' => 'users#create'
  get 'signup' => 'users#new'
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'
  get 'users/:id' => 'users#show' 

  get 'museums' => 'museums#index'
  get 'museums/search' => 'museums#search'
  get 'museums/:id' => 'museums#show'

  get 'posts/:museum_id/new' => 'posts#new'
  post 'posts/:museum_id/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'

  post 'likes/:post_id/create' => 'likes#create'
  post 'likes/:post_id/destroy' => 'likes#destroy'

  post 'favorites/:museum_id/create' => 'favorites#create'
  post 'favorites/:museum_id/destroy' => 'favorites#destroy'

  get 'notifications' => 'notifications#index'

  resources :maps, only: [:index]
end

app/models/museum.rb
class Museum < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :users, through: :favorites
    
    validates :name, {presence: true}
    validates :location, {presence: true}
    validates :introduction, {presence: true}
    validates :image_name, {presence: true}
    validates :opening_time, {presence: true}
    validates :closing_day, {presence: true}

    #locationは全て全角で県名からはじめる
    attribute :location, :string, default: '不明'
    attribute :introduction, :text, default: '詳細な情報がありません'
    attribute :image_name, :string, default: 'default_image.jpg'
    #opening_time, closing_dayは、英数字・記号は半角、それ以外は全角で統一
    attribute :opening_time, :string, default: '不明'
    attribute :closing_day, :string, default: '不明'
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index 
    @museums = Museum.all.page(params[:page]).per(10)
  end

  def show
    @museum = Museum.find_by(id: params[:id])
    @posts = Post.where(museum_id: params[:id])
  end

  def search
    if params[:name].present?
      @museums = Museum.where('name LIKE ?', "%#{params[:name]}%").page(params[:page]).per(10)
    else
      @museums = Museum.none.page(params[:page]).per(10)
    end
  end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/museums/_fiveStar.html.erb
<% star.times do %>
    <span class="fa fa-star text-warning"></span>
<% end %>
<% (5 - star).times do %>
    <span class="fa fa-star text-secondary"></span>
<% end %>

app/views/museums/_like.html.erb
<% if Like.find_by(user_id: @current_user.id, post_id: post.id) %>
    <%= link_to("/likes/#{post.id}/destroy", {method: :post, id: "Unlike #{post.id}"}) do  %>
        <span class="fa fa-heart text-danger"></span>
    <% end %>
<% else %>
    <%= link_to("/likes/#{post.id}/create", {method: :post, id: "Like #{post.id}"}) do %>
        <span class="fa fa-heart text-secondary"></span>
    <% end %>
<% end %>
<%= Like.where(post_id: post.id).count %>

app/views/museums/_map.html.erb
<p class="mt-3" id="address">
    <%= @museum.location %>
</p>
<div class="w-100" id="gmap" style="height:300px"></div>

<script>
function initMap() {
    var target = document.getElementById('gmap');  
    var address = document.getElementById('address').textContent; 
    var geocoder = new google.maps.Geocoder();  
    
    geocoder.geocode({ address: address }, function(results, status){
        if (status === 'OK' && results[0]){  
            let map = new google.maps.Map(target, {
                center: results[0].geometry.location,
                zoom: 16
            });
            let marker = new google.maps.Marker({
                position: results[0].geometry.location,
                map: map
            });
        }else{ 
            alert('失敗しました。理由: ' + status);
            return;
        }
    });
}
</script> 
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>&callback=initMap" async defer></script>  

app/views/museums/_museum.html.erb
<div class="container border rounded my-4">
    <div class="row">
        <div class="col-4 border-right">
            <%= image_tag "/museum_images/#{museum.image_name}", class: "index-image mx-auto d-block"%>
        </div>
        <div class="col-8">
            <h4 class="mt-2"><%= link_to(museum.name, "/museums/#{museum.id}") %></h4>
            <p><%= museum.location %></p>
            <% posts = museum.posts %>
            <% if posts.exists? %>
                <% starSum = posts.sum(:star) %>
                <% starAverage = starSum.fdiv(posts.count).round(2) %>
                <% museumStar = starSum.fdiv(posts.count).round %>
                <p>
                    <%= render partial: "fiveStar", locals: {star: museumStar} %>
                    <%= "#{starAverage} / 5.0 (#{museum.posts.count})" %>
                </p>
            <% else %>
                <p>
                    <% 5.times do %>
                        <span class="fa fa-star text-secondary"></span>
                    <% end %>
                    <%= "　" + "- - - (0)" %>
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/museums/_post.html.erb
<% user = User.find_by(id: post.user_id) %>
<h4><%= user.name %></h4>
<% star = post.star %>
<%= render partial: "museums/fiveStar", locals: {star: star} %>
<p><%= safe_join(post.content.split("\n"), tag(:br)) %></p>
<% if post.created_at != post.updated_at %>
    <p class="text-secondary">(編集済み)</p>
<% end %>

app/views/museums/_search_form.html.erb
<%= form_with url: museums_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :name, placeholder: "施設名を検索...", class: "ml-2 mt-5 w-75 form-control", id: "Museum name" %>
    <%= f.submit "検索", class: "ml-2 mt-2 btn btn-primary", id: "Search museum" %>
<% end %>

app/views/museums/index.html.erb
<div class="container mt-4">
    <div class="row my-2">
        <div class="col-3 border-right">
            <%= render "search_form" %>
        </div>
        <div class="col-9">
            <% @museums.each do |museum| %>
                <%= render partial: "museum", locals: {museum: museum} %>
            <% end %>
        </div>
    </div>
</div>

<div class="container mb-5">
    <%= paginate @museums %>
</div>

app/views/museums/search.html.erb
<div class="container mt-4">
    <div class="row my-2">
        <div class="col-3 border-right">
            <%= render "search_form" %>
        </div>
        <div class="col-9">
            <% if @museums.empty? %>
                <div class="alert alert-warning mx-auto w-75 mt-5 text-center">
                    検索ワードを含む美術館は見つかりませんでした
                </div>
            <% end %>
            <% if @museums.present? %>
                <h4 class="text-center">
                    <%= "”#{params[:name]}”を含む検索結果一覧" %>
                </h4>
            <% end %>
            <% @museums.each do |museum| %>
                <%= render partial: "museum", locals: {museum: museum} %>
            <% end %>
        </div>
    </div>
</div>

<div class="container mb-5">
    <%= paginate @museums %>
</div>

app/views/museums/show.html.erb
<div class="container mt-4 mb-5">
    <div class="row my-2">
        <div class="col-8 border-right mt-3">
            <div class="row">
                <div class="col-6">
                    <%= image_tag "/museum_images/#{@museum.image_name}", class: "show-image w-100" %>
                </div>
                <div class="col-6">
                    <h2>
                        <%= @museum.name %>
                        <% if @current_user %>
                            <% if Favorite.find_by(user_id: @current_user.id, museum_id: @museum.id) %>
                                <%= link_to("/favorites/#{@museum.id}/destroy", {method: :post, id: "Unfavorite"}) do %>
                                    <span class="fa fa-flag text-success"></span>
                                <% end %>
                            <% else %>
                                <%= link_to("/favorites/#{@museum.id}/create", {method: :post, id: "Favorite"}) do %>
                                    <span class="fa fa-flag text-secondary"></span>
                                <% end %>
                            <% end %>
                        <% else %>
                            <%= link_to("/login", {id: "Favorite without login"}) do %>
                                <span class="fa fa-flag text-secondary"></span>
                            <% end %>
                        <% end %>
                    </h2>
                    <% if @posts.exists? %>
                        <% starSum = @posts.sum(:star) %>
                        <% starAverage = starSum.fdiv(@posts.count).round(2) %>
                        <% museumStar = starSum.fdiv(@posts.count).round %>
                        <p>
                            <%= render partial: "fiveStar", locals: {star: museumStar} %>
                            <%= "#{starAverage} / 5.0 (#{@museum.posts.count})" %>
                        </p>
                    <% else %>
                        <p>
                            <% 5.times do %>
                                <span class="fa fa-star text-secondary"></span>
                            <% end %>
                            <%= "　" + "- - -" %>
                        </p>
                        <p>まだクチコミはありません</p>
                    <% end %>
                    <p>開館時間</p>
                    <p><%= simple_format @museum.opening_time %></p>
                    <p>休館日</p>
                    <p><%= simple_format @museum.closing_day %></p>
                </div>
            </div>
            <div class="border rounded p-3">
                <p><%= @museum.introduction %></p>
            </div>
            
            <div class="border-top mt-5 pt-4">
                <% if @current_user %>
                    <% myPost = @posts.find_by(user_id: @current_user.id) %>
                    <% if myPost %>
                        <div class="container border rounded mb-3">
                            <p>(あなたのクチコミ)</p>
                            <%= render partial: "post", locals: {post: myPost} %>
                            <%= render partial: "like", locals: {post: myPost} %>
                            <p><%= link_to("編集", "/posts/#{myPost.id}/edit") %></p>
                        </div>
                    <% else %>
                        <%= link_to("クチコミを投稿する", "/posts/#{params[:id]}/new") %>
                    <% end %>
                    <% posts = @posts.where.not(user_id: @current_user.id).page(params[:page]).per(3) %>
                    <% posts.each do |post| %>
                        <div class="container border rounded my-3">
                            <%= render partial: "post", locals: {post: post} %>
                            <%= render partial: "like", locals: {post: post} %>
                        </div>
                    <% end %>
                    <%= paginate posts %>
                <% else %>
                    <p class="text-center text-secondary mb-4">クチコミを投稿するにはログインが必要です</p>
                    <% posts = @posts.page(params[:page]).per(3) %>
                    <% posts.each do |post| %>
                        <div class="container border rounded my-3">
                            <%= render partial: "post", locals: {post: post} %>
                            <%= link_to("/login", {id: "Like #{post.id} without login"}) do %>
                                <span class="fa fa-heart text-secondary"></span>
                            <% end %>
                            <%= Like.where(post_id: post.id).count %>
                        </div>
                    <% end %>
                    <%= paginate posts %>
                <% end %>
            </div>
        </div>

        <div class="col-4">
            <%= render "map" %>
        </div>
    </div>
</div>